### ISSUE TITLE
`:Telescope repo` returns an error (as expected)

### ISSUE THREAD

**Issue by cljoly** [cljoly/telescope-repo.nvim#16]
There have been reports in #10 of the following error:
```
E5108: Error executing lua ...id/.vim/plugged/telescope.nvim/lua/telescope/command.lua:184: attempt to call a nil value
stack traceback:
        ...id/.vim/plugged/telescope.nvim/lua/telescope/command.lua:184: in function 'run_command'
        ...id/.vim/plugged/telescope.nvim/lua/telescope/command.lua:241: in function 'load_command'
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
```
When running `:Telescope repo`.

Maybe we could have a default subcommand running when none is supplied (maybe `list`, as it only requires `fd`)

_Originally posted by @DavidEGx in https://github.com/cljoly/telescope-repo.nvim/issues/10#issuecomment-992546874_

**Comment by marcelarie** [comment]
I have the same error

**Comment by cljoly** [comment]
Yeah, I think everyone would get an error.

The documentation advises to use
```
:Telescope repo list
```
or other subcommands.

**Comment by marcelarie** [comment]
> Yeah, I think everyone would get an error.
> 
> The documentation advises to use
> 
> ```
> :Telescope repo list
> ```
> 
> or other subcommands.


I understand that the command is `:Telescope repo list`, but I think handeling that error 
will make it more solid. A little menu will the options that `repo` gives will be a good solution.

**Comment by cljoly** [comment]
> I understand that the command is `:Telescope repo list`, but I think handeling that error will make it more solid. A little menu will the options that `repo` gives will be a good solution.

Oh, ok. Yeah, I agree, I just don’t know how to handle the error.
