### ISSUE TITLE
Enters `find files` in Normal mode, would want Insert mode

### ISSUE THREAD

**Issue by molleweide** [cljoly/telescope-repo.nvim#22]
For both `list` and `cached_list` repo enters repositories
find files in normal modes which means that I have to press eg. `a` or `i`
in order to be able to search files. Ie. it inccures one extra
keypress. Are you experiencing this Clement? Or is this a feature?

this issue was created with `octo.nvim`. This is just amazing.
If you pwd=telescope repo. then you can just run
`:Octo issue list` and telescope will list all issues. then just ennter
the issue you want to edit or you can create a new issue from neovim
with `Octo issue create`

**Comment by molleweide** [comment]
test test

**Comment by cljoly** [comment]
> For both list and cached_list repo enters repositories
find files in normal modes which means that I have to press eg. a or i
in order to be able to search files. Ie. it inccures one extra
keypress. Are you experiencing this Clement? Or is this a feature?

I don’t experience it, it stays in insert mode for me. I agree that it’s annoying, there might be a way to fix it…

**Comment by cljoly** [comment]
Have you tried updating all your plugin? Did this behavior persist?

**Comment by molleweide** [comment]
Allright good to hear that you dont have the issue. I will do some testing and report back.

**Comment by cljoly** [comment]
Thinking more about this, I tried to reproduce the approach from https://github.com/nvim-telescope/telescope-project.nvim. Do you encounter the bug with this plugin as well @molleweide?

**Comment by molleweide** [comment]
Hmm ill test and report back

**Comment by cljoly** [comment]
Thanks!

**Comment by molleweide** [comment]
Havent had so much time for tele repo in the last few days fyi

**Comment by cljoly** [comment]
No worries, thanks for the update!

**Comment by cljoly** [comment]
This might be a fix: https://github.com/nvim-telescope/telescope-project.nvim/commit/d317c3cef6917d650d9a638c627b54d3e1173031

**Comment by cljoly** [comment]
The fix is now on the `dev` branch. I believe this now solved, feel free to reopen if you encounter the issue again *(from the `dev` branch)*
