### ISSUE TITLE
Telescope search_dirs

### ISSUE THREAD

**Issue by phortonssf** [cljoly/telescope-repo.nvim#24]
Is this option supported? As of right now I can't get it to work.

`:lua require'telescope'.extensions.repo.cached_list{search_dirs = {"~/.dotfiles/nvim/.config/nvim/plugin"}}`

**Comment by cljoly** [comment]
Hi, thanks for opening this issue!
That seems useful, I’m looking into implementing it.

**Comment by cljoly** [comment]
This is now implemented (#26)
