### ISSUE TITLE
Some commands crash after telescope-repo plugin update

### ISSUE THREAD

**Issue by lxgreen** [cljoly/telescope-repo.nvim#32]
OS: Mac OS
Neovim: 0.6.1

The issue reproduces since plugin update that added PRs #25 , #26, #30 

Example commands that crash: `Telescope repo list`, also `(telescope.health).check` fails with the same error. 

Error message:
```bash
E5108: Error executing lua ...escope-repo.nvim/lua/telescope/_extensions/repo/list.lua:26: bad argument #1 to 'ipairs' (table expected, got nil)
stack traceback:
        [C]: in function 'ipairs'
        ...escope-repo.nvim/lua/telescope/_extensions/repo/list.lua:26: in function 'prepare_command'
        ...escope-repo.nvim/lua/telescope/_extensions/repo/main.lua:198: in function <...escope-repo.nvim/lua/telescope/_extensions/repo/main.lua:195>
        ...re/nvim/plugged/telescope.nvim/lua/telescope/command.lua:182: in function 'run_command'
        ...re/nvim/plugged/telescope.nvim/lua/telescope/command.lua:255: in function 'load_command'
        [string ":lua"]:1: in main chunk

```

**Comment by lxgreen** [comment]
seems like configuration issue -- `search_dirs` is mandatory. maybe it is worth to mention that this parameter is required.

**Comment by lxgreen** [comment]
still crashes within telescope checkhealth, reopening

**Comment by cljoly** [comment]
Sorry about that, I'll try to reproduce this error ASAP. Thanks for providing the nvim version that should be helpful.

**Comment by cljoly** [comment]
Running `git bisect`, this seem to have been introduced with commit a0384bc2eaf589c8184d9c4480ba9ab0513edf1a

**Comment by cljoly** [comment]
I’ve merged a fix, You should now have:
* health checks passing,
* `Telescope repo list` working without issues.
Feel free to reopen though if you still have the same issue on the latest master branch.

**Comment by cljoly** [comment]
Thanks @lxgreen for your report!

**Comment by cljoly** [comment]
#34 Should reduce the likeliness of this type of problem reoccuring.
