### ISSUE TITLE
Global telescope-repo configuration 

### ISSUE THREAD

**Issue by Chetan496** [cljoly/telescope-repo.nvim#38]
Hi All

I am trying to  configure telescope-repo. I want to set the `fd_opts` and `search_dirs` in telescope configuration. I tried, but the configuration is not working.

Please find the snippet from my `init.lua`

```
require("telescope").load_extension("file_browser")
require("telescope").load_extension("repo")

require("telescope").setup {
  extensions = {
     repo = {
	list = {
          fd_opts = {
           "--no-ignore-vcs",
          },
          search_dirs = {
           "~/my_projects"
          }

	}     
     }
  }
}

require("telescope").setup {
  extensions = {
	list = {
          fd_opts = {
           "--no-ignore-vcs",
          },
          search_dirs = {
           "~/my_projects"
          }

	}     
  }
}

```

I tried the below snippet as well

```
require("telescope").setup {
  extensions = {
     repo = {
	
          fd_opts = {
           "--no-ignore-vcs",
          },
          search_dirs = {
           "~/my_projects"
          }

     }
  }
}

```

Both are not working. 
Some context: my $HOME dir is under Git. But not every subdir under $HOME is under git.  The `my_projects` is a separate directory which contains subdirectories each of which is a Git repo.

Any idea what is wrong?

**Comment by Chetan496** [comment]
@cljoly - please help

**Comment by cljoly** [comment]
I don't think that this is supported, but I wouldn't mind adding that feature

**Comment by cljoly** [comment]
I should be able to take a deeper look in the next few days

**Comment by Chetan496** [comment]
Thanks. Meanwhile I will map the lua command for `Telescope repo list` with fd options and use that

**Comment by cljoly** [comment]
I think that defining a custom `setup` entry in the table that the extension returns to telescope when initialized should work. I’ll have a PR soon.

**Comment by Chetan496** [comment]
> I think that defining a custom `setup` entry in the table that the extension returns to telescope when initialized should work. I’ll have a PR soon.

That's great!

**Comment by cljoly** [comment]
#41 should solve your problem (I’ve a fixed version of your snippet as an example: https://github.com/cljoly/telescope-repo.nvim/pull/41/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R109).
