### ISSUE TITLE
Bad argument to 'insert' (table expected, got string)

### ISSUE THREAD

**Issue by sgoudham** [cljoly/telescope-repo.nvim#39]
## The Issue

Hi, I've been trying to configure this extension and cannot get it to work, the preview is always an empty box. 

I've included the optional loading

`require("telescope").load_extension("repo")`

but, when running `:checkhealth telescope._extensions.repo`, I get the following output:

```shell
telescope._extensions.repo: require("telescope._extensions.repo.health").check()
========================================================================
  - ERROR: Failed to run healthcheck for "telescope._extensions.repo" plugin. Exception:
    function health#check, line 20
    Vim(eval):E5108: Error executing lua ...scope-repo.nvim/lua/telescope/_extensions/repo/utils.lua:38: bad argument #1 to 'insert' (table expected, got string)
    stack traceback:
    [C]: in function 'insert'
    ...scope-repo.nvim/lua/telescope/_extensions/repo/utils.lua:38: in function 'find_markdown_previewer_for_document'
    ...cope-repo.nvim/lua/telescope/_extensions/repo/health.lua:82: in function 'check_previewer'
    ...cope-repo.nvim/lua/telescope/_extensions/repo/health.lua:97: in function 'check'
    [string "luaeval()"]:1: in main chunk
```

I've not provided any config so I'm unsure why it's erroring, would appreciate any help in fixing this if it's a client issue.

## Diagnostic Information
**nvim**: 0.7
**telescope**: [latest](https://github.com/nvim-telescope/telescope.nvim/commit/d3aad43b3fcf707052f7dd8a7c7072fa69773f3c)
**telescope-repo**: 0.3.0
**os**: Windows 11

**Comment by cljoly** [comment]
Thanks for taking the time to report this issue.

Just to be sure, you are using neovim and this plugin on windows “natively”, not with the Windows Subsystem for Linux, right?

**Comment by sgoudham** [comment]
Yup, just on windows 11 natively.

**Comment by cljoly** [comment]
https://github.com/cljoly/telescope-repo.nvim/commit/b7fb147317ffb706215ef142b9ef4d6d81976015 should be a fix, but I want to test it some more before merging it to master.

Disclaimer: I’m not using Windows at all, so it’s quite hard to test if this will work. You are welcome to come back and report any further issues you might encounter though.

**Comment by sgoudham** [comment]
Thanks so much! I'll try to test this locally too by making the same changes you made but to my local version of telescope-repo

**Comment by cljoly** [comment]
> Thanks so much! I'll try to test this locally too by making the same changes you made but to my local version of telescope-repo

You can just install the `dev` branch, it’s easier :) What package manager do you use?

**Comment by sgoudham** [comment]
Ah yeah, that's a smarter idea. I use Vim Plug. 
I'll pull down the dev branch on that, thanks 👍

**Comment by cljoly** [comment]
No worries, happy to help. 

You can also follow this [post’s section](https://cj.rs/blog/tips/nvim-plugin-development/#load-local-plugin-version), to make it easier for you to make local changes if you wish to.

**Comment by sgoudham** [comment]
So there's good news and bad news 😅 

The good news is that the original error raised above in the issue seems to have been resolved. The bad news being that we're onto a different error now :D 

I'll raise another issue for that one so if you want, feel free to close this one (once you're happy with your testing of course!)
