### ISSUE TITLE
Using 'batcat' for finding 'bat'

### ISSUE THREAD

**Issue by jalcine** [cljoly/telescope-repo.nvim#47]
On Debian-based systems (I'm using [elementaryOS](https://elementary.io/)), I noticed that one would have to make a symlink to <code>batcat</code>, the binary that most programs expect when using <code>bat</code>

.

Would you be open to a PR to add a check/lookup for <code>batcat</code> and use it if it exists and if not, use <code>bat</code>? I see the relevant line would be [here](https://github.com/cljoly/telescope-repo.nvim/blob/78dedcf656288c196118af9e41d666fac62d57c4/lua/telescope/_extensions/repo/utils.lua#L25)

(Originally published at: https://jacky.wtf/2022/8/y-B0)

**Comment by cljoly** [comment]
Thanks for considering contributing to this plugin. Yes I'm open to a PR that would do that, plus you seem on the right track to do it.

I’m looking forward to reviewing your PR, please let me know if you need any help!

**Comment by cljoly** [comment]
@jalcine do you still want to make a PR.
