### ISSUE TITLE
Endless loop when execute autocmd_lcd on Windows

### ISSUE THREAD

**Issue by langjinet** [cljoly/telescope-repo.nvim#55]
When open file like D:\tmp\test.js on Windows - and D:\tmp doesn't exist on the config path (project_paths)

Path:new("D:"):parent() will go back to app directory.

``` lua
while not (project_paths[abs_buf_path] or abs_buf_path == "/") do
end

if abs_buf_path ~= "/" then
```

**Comment by cljoly** [comment]
Thanks for taking the time to report this issue.

I can reproduce that with:
```lua
local path = require("plenary.path")
local p = path.new("D:\\")
print(p.filename)
-- Prints "D:\\"
print(p:parent().filename)
-- Prints "/home/user"
```
Even with a forward slash:
```lua
local path = require("plenary.path")
local p = path.new("D:/")
print(p.filename)
-- "D:/"
print(p:parent().filename)
-- "/home/user"
```

That seems to be be an issue in to [Plenary](https://github.com/nvim-lua/plenary.nvim), which would need to be reported there. When I have some time, I might look into fixing this in Plenary. But for for a quicker fix, you might want to report it there and work with them to fix this.

**Comment by langjinet** [comment]
Thanks for your time. Got a work-around solution, of course it is so good for performance if we implement additional check with a counter and a '%a:' pattern check.
